name: emoji_rating_bar
description: Smooth animated rating bar for customer and service feedback, equipped with customizable emotion and mood bars with emoji.
version: 0.0.1
homepage: https://github.com/KinjalDhamat312/EmojiRatingBar

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

   assets:
     - assets/